### ISSUE TITLE
Add support for MongoDB

### ISSUE THREAD

**Issue by webteckie** [keystonejs/storage#1]
It is becoming increasingly common to store certain content that would otherwise be in files in the database.   This issue specifically calls for MongoDB support. It should be possible to configure MongoDB and content would be stored in a document under a given collection.

**Comment by grabbou** [comment]
Thanks @webteckie for your input. I quite like that idea, especially in terms of text / code files we might store (like CSS files users can edit or something). 

But we do need a kind of API (using express) to display those files to the users (`address`/`your_custom_path`/`name_of_the_file_with_extension` - `http://url.com/assets/files/demo.css`). I'd rather put that in separate repository, as storage-views or something. We will need that anyway for displaying local files but i would like to keep number of dependencies as small as possible.

What you think?

**Comment by webteckie** [comment]
@grabbou we may be able to leverage something like https://github.com/aheckmann/gridfs-stream for the access.  That seems to use MongoDB's GridFS file system.  In the keystone side, we would need to configure static routes of this type. I think -- unless if your Storage API makes the access transparent to clients like keystone then it would probably be the Storage API that would host the gridfs-stream plugin?

**Comment by grabbou** [comment]
Yeah, that's cool. We can definitely use that to make everything streams driven! Storage API should host that to make it more portable and accessible in other projects. AFAIK it's going to be almost the same as e.g. `AmazonClient` that uses streams as well.

In terms of routes -> for the very beginning, we can leave static routes up to keystone, but it'd be quite useful to have another package registering them for us.

I am going to give that a go as soon as I finish fighting with FTP clients that are quite abandoned unfortunately.

**Comment by webteckie** [comment]
You may want to also take a look at https://www.npmjs.org/package/gridfs-locking-stream

Btw, does anyone have an urgent need for the FTP subsystem?   If not, perhaps give the MongoDB storage higher priority?

**Comment by grabbou** [comment]
Yep, I've already stopped working on that due to lack of reliable FTP library we can use. So MongoDB & Filesystem are the only ones we need before finishing. ETA ~2 days probably.

Thanks for linking that as well. I'll give it a go shortly.

**Comment by grabbou** [comment]
This is already implemented in latest dev release. Will be probably tweaked in the future. Thanks for suggesting `GridFS` package to integrate.

**Comment by patrickwilmes** [comment]
Is their now a gridfs support in Keystone or is their any best practice to store binaries in gridfs?
