### ISSUE TITLE
Add Provider Types to README.md

### ISSUE THREAD

**Issue by webteckie** [keystonejs/storage#7]
Perhaps add the provider types (as used programmatically) to README.md.  For example, the Configuration section mentions:

```
provider: Storage.Providers.AmazonS3
```

What are the others?  Maybe just as easy as putting them in parentheses in where it lists them at "Available storage providers:"

**Comment by grabbou** [comment]
Hi @webteckie, that's very cool idea. Would you like to do a PR for that? List of supported providers is given in `lib/providers/index.js` so you can take a look at their names.

Basically, Readme needs to be completely rewritten but as long as I am not fluent in writing them -> any help is welcome!

**Comment by webteckie** [comment]
Ok let's see if I get some time ☺

**Comment by grabbou** [comment]
I hope you do! :dash: It's fun to develop software with somebody else than alone :)
